services:
  postgres:
    image: postgres:12
    ports:
      - 15432:5432
    environment:
      POSTGRES_DB: mayakenergy
      POSTGRES_USER: mayakenergy
      POSTGRES_PASSWORD: mayakenergy
  microocpp:
    image: matthx/microocppsimulator:latest
    ports:
      - 8000:8000
