networks:
  default:
  nginx-proxy:
    external: true

services:
  pg:
    image: postgres:16
    networks:
      - default
    ports:
      - 5432:5432
    environment:
      POSTGRES_DB: mayakenergy
      POSTGRES_USER: mayakenergy
      POSTGRES_PASSWORD: mayakenergy
    volumes:
      - mayak-online-data:/var/lib/postgresql/data

  app:
    image: registry.devhub.local/mayak.energy:latest
    networks:
      - default
      - nginx-proxy
    environment:
      DB_HOST: pg
      DB_PORT: 54321
      DB_BASE: mayakenergy
      DB_USERNAME: mayakenergy
      DB_PASSWORD: mayakenergy
      VIRTUAL_HOST: energy.*
      VIRTUAL_PORT: 8080

volumes:
  mayak-online-data:
