server:
  port: ${SERVER_PORT:8080}
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    env:
      show-values: always
logging:
  level:
    '[online.mayak.energy]': ${LOGGING_LEVEL:DEBUG}
    '[org.springframework.web]': INFO
    '[org.hibernate.SQL]': INFO
    '[org.thymeleaf]': INFO
spring:
  application:
    name: Маяк.Энергия
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${DB_HOST:devhub.local}:${DB_PORT:15432}/${DB_BASE:mayakenergy}
    username: ${DB_USERNAME:mayakenergy}
    password: ${DB_PASSWORD:mayakenergy}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
  docker:
    compose:
      enabled: false
      lifecycle-management: start-and-stop
      profiles:
        active: postgres-12
  flyway:
    enabled: true
  jpa:
    open-in-view: false
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML
ocpp:
  auto-register-new-charge-point: true
