name: deploy
on: 
  push:
    branches:
      - main
jobs:
  java-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Java 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'adopt'

      - name: Set up Maven
        uses: stCarolas/setup-maven@v5
        with:
          maven-version: 3.8.2

      - name: Build and package project
        run: mvn -f pom.xml clean package

      - name: Rename the artifact
        run: cp target/mayak.energy-0.0.1-SNAPSHOT.jar mayak.energy-${{ github.sha }}.jar

      - name: Save the artifact
        uses: actions/upload-artifact@master
        with:
          name: mayak.energy
          path: mayak.energy-${{ github.sha }}.jar
